version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: remote_health
      POSTGRES_USER: remote_health
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:


# version: '3.7'
# services:
#   postgres:
#     image: postgres:13
#     container_name: postgres_db
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_DB: ${DATABASE_NAME}
#       POSTGRES_USER: ${DATABASE_USER}
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
#     ports:
#       - '5050:80'
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin

# volumes:
#   postgres_data:
#   pgadmin-data:
